#开启debug模式
debug: true

#激活指定配置
spring:
  profiles:
    active: dev

#设置http编码，解决乱码问题
  http:
    encoding:
      enabled: true
      charset: UTF-8
      force: true

#设置端口
server:
  servlet:
    context-path: /something
  port: 8080
