server:
  port: 8080
  servlet:
    context-path: /clockin
spring:
  application:
    name: clockin
  profiles:
    active: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/clockin?useUnicode=true&characterEncoding=utf8&serverTimezone=Hongkong
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  redis:
    spring.redis.database: 0 # Redis数据库索引（默认为0）
    spring.redis.host: localhost # Redis服务器地址
    spring.redis.port: 6379 # Redis服务器连接端口
    spring.redis.password: root # Redis服务器连接密码（默认为空）
    spring.redis.pool.max-active: 8 #连接池最大连接数（使用负值表示没有限制）
    spring.redis.pool.max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
    spring.redis.pool.max-idle: 8 # 连接池中的最大空闲连接
    spring.redis.pool.min-idle: 0 # 连接池中的最小空闲连接
    spring.redis.timeout: 1000 # 连接超时时间（毫秒）

mybatis:
  mapper-locations: classpath*:/mapper/**Mapper.xml,classpath*:/mapper/ClockInMapper/**Mapper.xml
  typeAliasesPackage: org.bobo.clockin.bean
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
logging:
  file: src/main/resources/log/clockin.log
  level:
    com.test: debug
